from __future__ import annotations

import shlex
import subprocess
from dataclasses import dataclass

from ..config import ConnectorConfig
from ..models import ExecutionResult, VerificationResult
from ..state import WorkflowState


@dataclass
class CommandResult:
    stdout: str
    stderr: str
    returncode: int


class KubectlKubernetesClient:
    def __init__(self, config: ConnectorConfig):
        self.config = config

    def _base_command(self) -> list[str]:
        command = [self.config.kubectl_command]
        if self.config.kubectl_context:
            command.extend(["--context", self.config.kubectl_context])
        if self.config.kubeconfig_path:
            command.extend(["--kubeconfig", self.config.kubeconfig_path])
        return command

    def _run(self, argv: list[str]) -> CommandResult:
        completed = subprocess.run(argv, capture_output=True, text=True, check=False)
        return CommandResult(
            stdout=completed.stdout.strip(),
            stderr=completed.stderr.strip(),
            returncode=completed.returncode,
        )

    def _run_capture(self, suffix: list[str]) -> str:
        result = self._run([*self._base_command(), *suffix])
        if result.returncode == 0:
            return result.stdout or "(command succeeded with no stdout)"
        return f"ERROR ({result.returncode}): {result.stderr or result.stdout}"

    def collect_context(self, state: WorkflowState) -> dict[str, list[str]]:
        namespace = state["namespace"]
        workload = state["workload"]
        return {
            "events": [
                self._run_capture(["-n", namespace, "get", "events", "--sort-by=.lastTimestamp"]),
            ],
            "logs": [
                self._run_capture(
                    ["-n", namespace, "logs", f"deployment/{workload}", "--all-containers=true", "--tail=100"]
                )
            ],
            "metrics": [
                self._run_capture(["-n", namespace, "get", "pods", "-o", "wide"]),
            ],
            "manifests": [
                self._run_capture(["-n", namespace, "get", "deployment", workload, "-o", "yaml"]),
            ],
        }

    def execute_plan(self, state: WorkflowState) -> ExecutionResult:
        if state.get("approval_required") and state.get("approval_status") != "approved":
            return ExecutionResult(
                status="skipped",
                details="Execution was skipped because the plan was not approved.",
                commands=[],
            )

        commands = [item["command"] for item in state.get("plan", [])]
        if not self.config.allow_mutations:
            return ExecutionResult(
                status="blocked",
                details="Mutating commands are disabled. Set AI_OPS_ALLOW_MUTATIONS=true to enable execution.",
                commands=commands,
            )

        outputs: list[str] = []
        for command in commands:
            if any(token in command for token in {"|", "&&", ";", "||", "$(", "`"}):
                return ExecutionResult(
                    status="failed",
                    details=f"Refused to execute shell-style command generated by planner: {command}",
                    commands=commands,
                )
            argv = shlex.split(command)
            if not argv:
                continue
            if argv[0] not in {"kubectl", "helm"}:
                return ExecutionResult(
                    status="failed",
                    details=f"Refused to execute unsupported command prefix: {argv[0]}",
                    commands=commands,
                )
            result = self._run(argv)
            outputs.append(result.stdout or result.stderr)
            if result.returncode != 0:
                return ExecutionResult(
                    status="failed",
                    details=result.stderr or result.stdout or f"Command failed: {command}",
                    commands=commands,
                )

        return ExecutionResult(
            status="completed",
            details="\n\n".join(filter(None, outputs)) or "All commands completed successfully.",
            commands=commands,
        )

    def verify(self, state: WorkflowState) -> VerificationResult:
        namespace = state["namespace"]
        workload = state["workload"]

        rollout = self._run(
            [*self._base_command(), "-n", namespace, "rollout", "status", f"deployment/{workload}", "--timeout=60s"]
        )
        pods = self._run([*self._base_command(), "-n", namespace, "get", "pods"])

        success = rollout.returncode == 0
        signals = []
        if rollout.stdout:
            signals.append(rollout.stdout)
        if pods.stdout:
            signals.append(pods.stdout)
        if rollout.stderr:
            signals.append(rollout.stderr)

        return VerificationResult(
            success=success,
            summary=(
                "Rollout verification succeeded."
                if success
                else "Rollout verification failed. Inspect rollout status and pod readiness."
            ),
            signals=signals,
        )
